name: rpgstats.stack

services:
  db:
    container_name: rpgstats-db
    image: postgres:16.3
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 512mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: RpgStats
      POSTGRES_PASSWORD: RpgStats
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U RpgStats"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rpgstats-network

  rpgstats.webapi:
    image: rpgstats.webapi
    build:
      context: .
      dockerfile: RpgStats.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5137"
      - "7073"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - rpgstats-network

  nginx:
    image: nginx:alpine
    ports:
      - "10000:80"
      - "10001:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert:/etc/nginx/cert:ro
    depends_on:
      - rpgstats.webapi
    networks:
      - rpgstats-network
  
networks:
  rpgstats-network:
    driver: bridge