@HostAddress = http://localhost:5137

GET {{HostAddress}}/api/characters/
Accept: application/json

###

GET {{HostAddress}}/api/characters/byGame?gameId=1
Accept: application/json

###

GET {{HostAddress}}/api/characters/byName?name=Cloud
Accept: application/json

###

