version: '3.9'

name: rpgstats-dev-stack

services:
  db:
    container_name: rpgstats-dev-db
    image: postgres:16.3
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 512mb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: RpgStats
      POSTGRES_PASSWORD: RpgStats
